version: "3.1"

services:
  site:
    build: ./build/site
    container_name: oj-site
    restart: always
    environment:
      - WAIT_HOSTS=db:3306
    ports:
      - 80:80
      - 443:443
      - 9999:9999
      - 9998:9998
      - 15100:15100
      - 15101:15101
      - 15102:15102
    volumes:
      - $PWD/data/site:/site
      - $PWD/data/problems:/problems
    depends_on:
      - db

  judge:
    build: ./build/judge
    container_name: oj-judger
    privileged: true
    restart: always
    depends_on:
      - site
    volumes:
      - $PWD/data/problems:/problems
    env_file: judge1.env

  db:
    image: mariadb:10.3.10
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=ispace@240
      - MYSQL_DATABASE=isoj
      - MYSQL_USER=root
      - MYSQL_PASSWORD=ispace@240
    volumes:
      - $PWD/data/database:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
