#!/bin/bash
cd $(dirname $(dirname $0)) || exit

docker-compose exec $COMPOSE_EXEC_FLAGS site /bin/bash -c "\
    bash ./make_style.sh && \
    echo yes | python3 manage.py collectstatic && \
    python3 manage.py compilemessages && \
    python3 manage.py compilejsi18n"